/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14.2/userguide/multi_project_builds.html in the Gradle documentation.
 */
pluginManagement {
    repositories {
        maven {
            url = uri("https://maven.aliyun.com/repository/gradle-plugin/")
        }
        maven {
            url = uri("https://mirrors.cloud.tencent.com/nexus/repository/gradle-plugin/")
        }
        gradlePluginPortal()
    }
}
//plugins {
//    // Apply the foojay-resolver plugin to allow automatic download of JDKs
//    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
//}

rootProject.name = "LocalApplication"
include("app")
