spring:
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        base-url: https://api.deepseek.com
        api-key: ${DEEPSEEK_API_KEY}
        model: deepseek-chat
        temperature: 0.7
        max-tokens: 2048
        top-p: 1.0
        frequency-penalty: 0.0
        presence-penalty: 0.0
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
secure:
  ignored:
    urls:
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-resources/**
      - /actuator/**
management:
  info:
    env:
      enabled: true
    defaults:
      enabled: true
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
      baseUrl: /actuator
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    shutdown:
      enabled: true
logging:
  level:
    root: INFO
#    org.springframework.boot.actuate: DEBUG