spring:
  ai:
    deepseek:
      base-url: https://api.deepseek.com
      api-key: {to_be_replaced}
      chat:
        base-url: https://api.deepseek.com
        api-key: {to_be_replaced}
        model: deepseek-chat
        temperature: 0.7
        max-tokens: 2048
        top-p: 1.0
        frequency-penalty: 0.0
        presence-penalty: 0.0
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
secure:
  ignored:
    urls:
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-resources/**
      - /actuator/**
