apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-application
  namespace: local-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-application
  template:
    metadata:
      labels:
        app: local-application
    spec:
      containers:
      - name: local-application
        image: 0.0.0.0:5050/local-application-image:v1.0
        ports:
        - containerPort: 8080
        env:
        - name: DEEPSEEK_API_KEY
          valueFrom:
            secretKeyRef:
              name: deepseek-secret
              key: api-key
---
apiVersion: v1
kind: Service
metadata:
    name: local-application-service
    namespace: local-test
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8080
  selector:
    app: local-application
---